#!/usr/bin/env bash

source ./packages.sh
source ../../sh/virtualbox-debian.sh
source ../../sh/vagrant-debian.sh
source ../../sh/tmux-1.9a.sh
source ../../sh/chrome-debian.sh
source ../../sh/maven3.0.5.sh
source ../../sh/lynx2.8.7.sh
source ../../sh/s3cmd.sh
source ../../sh/ack-2.12.sh
source ../../sh/vim-7.4-debian.sh
source ../../sh/weechat-debian.sh
source ../../sh/eclipse-4.1.4.sh
source ../../sh/jq-1.4.sh
source ../../sh/mongodb-linux-x86_64-2.6.4.sh
source ../../sh/docker_latest-debian.sh
source ../../sh/packer-0.7.2-x86_64.sh
source ../../sh/vimpager-debian.sh
source ../../sh/lame-3.99-debian.sh
source ../../sh/node_js-0.12.2.sh
source ../../sh/ls.sh
source ../../sh/rofi-0.15.4.sh
