# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "postgres2"
  config.vm.network "forwarded_port", guest: 5432, host: 7000
  config.vm.provision "shell", inline: "service iptables stop"
end
