# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "postgres2"
  config.vm.provision "shell", path: "bootstrap.sh", :privileged => false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.ssh.username = "postgres"
  config.ssh.private_key_path = "../../keys/postgres_key"
end
