#!/usr/bin/env ruby

forge "https://forgeapi.puppetlabs.com"

# use dependencies defined in Modulefile
modulefile

mod "puppetlabs/firewall"
mod "puppetlabs/postgresql"
mod "puppetlabs/java"
mod "mkrakowitzer/jira", :git => "git://github.com/brycejohnson/puppet-jira.git"
mod "rtyler/jenkins", :git => "git://github.com/jacderida/puppet-jenkins.git"
