# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.box = "ubuntu-1204x64"
	config.vm.box_url = "https://jacderida-vagrant-boxes.s3.amazonaws.com/ubuntu-1204x64.box"
	config.vm.provision "shell", path: "bootstrap.sh"
	config.vm.provider :virtualbox do |vb|
		vb.gui = true
	end
	if ENV['http_proxy']
		config.apt_proxy.http  = ENV['http_proxy']
	end
end
